config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'weather_forecasts#index'
  get '/current_weather', to: 'weather_forecasts#current_weather', as: 'current_weather'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application Controller
class ApplicationController < ActionController::Base
end

app/controllers/weather_forecasts_controller.rb
# frozen_string_literal: true

# This controller class provides info related to weather forecast
class WeatherForecastsController < ApplicationController
  def index; end

  def current_weather
    location = LocationFinderService.call(params[:address])
    if location.nil?
      @error = {message: 'Location not found', code: 422} 
    else
      @weather, @cached = WeatherForecastService.call(location)
      @error = {
                  message: 'Unable to fetch weather forcast for this address',
                  code: 422
               } if @weather.nil?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_forecasts_helper.rb
module WeatherForecastsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherForecast</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if @error %>
      <%= render "shared/error", locals: {error: @error} %> 
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error.html.erb
<div class="error-container">
  <h1 class="error-title">Oops! Something went wrong</h1>
  <p class="error-message"><%= @error[:message] %></p>
  <p class="error-code">Error code: <%= @error[:code] %></p>
</div>

app/views/weather_forecasts/current_weather.html.erb
<% if @weather && @weather['cod'] == 200 %>
  <h1 class="weather-heading">Current Weather</h1>

  <% presenter = WeatherForecastPresenter.new @weather %>

  <dl class="weather-info">
    <dt class="weather-label">Weather:</dt>
    <dd><%= presenter.weather %></dd>

    <dt class="weather-label">Weather Description:</dt>
    <dd><%= presenter.description %></dd>

    <dt class="weather-label">Current Temperature:</dt>
    <dd><%= presenter.current_temp %></dd>

    <dt class="weather-label">Minimum Temperature:</dt>
    <dd><%= presenter.min_temp %></dd>

    <dt class="weather-label">Maximum Temperature:</dt>
    <dd><%= presenter.max_temp %></dd>

    <dt class="weather-label">Humidity:</dt>
    <dd><%= presenter.humidity %></dd>

    <% if @cached %>
      <dt class="weather-label">Response from Cache:</dt>
      <dd>Yes</dd>
    <% end %>
  </dl>
<% end %>

app/views/weather_forecasts/index.html.erb
<h1>Weather Forecast</h1>

<%= form_tag(current_weather_path, method: :get) do %>
  <%= label_tag(:address, 'Address:') %>
  <%= text_field_tag(:address) %>
  <%= submit_tag('Get Forecast') %>
<% end %>